### ISSUE TITLE
Consertar erro da home

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-api#112]
Hoje a pagina nao retorna nenhum dado na home, a expectativa era ter uma lista dos endpoints da API

![image](https://user-images.githubusercontent.com/20743819/209713645-ae0fe5d4-717c-49ab-ab2e-4bdc1ff9eb4d.png)

**Comment by yxuo** [comment]
PR criado em: #110 
---
### Objetivo 
- Apresentar os endpoints corretamente na raiz.
- Issue:
![Image](https://user-images.githubusercontent.com/13617185/209699426-bf1f35dc-bf47-4a8f-88ca-f37b329f2b55.png)

### Tarefas

- [x] Criar branch `feat/home-api` de `dev`
- [x] Subir alteração
- [x] Enviar PR
- [ ] Aceitar PR
