### ISSUE TITLE
Adicionar filtro de `stop_name` em `stops`

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-api#115]
## Objetivo

Permitir que o usuário (FE) pesquise no app pelo nome da estação (stop_name), para isso precisamos filtar por stop_name o end_point stops.

No front, a atual busca é disparada quando a subtring atinge 4 caracteres. 
Limitar a quantidade de resultados (10 resultados).

**Comment by yxuo** [comment]
## Andamento

- [x] Criar novo ramo `feat/stop_name-stops` baseado em `feat/trip_id-frequencies`
- [x] Criar filtro de `stop_name` em stops
- [x] Permitir pesquisar mais de 1 `stop_id` em stops
- [x] Adicionar parâmetro no README
- [ ] Aguardar PRs pendentes
- [ ] Criar PR para `dev`
- [ ] Aceitar PR
- [ ] Diagramar parâmetro no [Miro](https://miro.com/app/board/o9J_lqIY7Eg=/)

**Comment by gmartinsoc** [comment]
Estamos limitando pela paginação cujo padrão é 20 objetos, precisamos confirmar se o retorno por pagina é adequado ao requisito do front.

**Comment by yxuo** [comment]
PR criado em: #126
---
Também é possível ver neste card em **Linked pull requests**, no painel lateral

**Comment by yxuo** [comment]
PR aceito.
Falta confirmar com @gmartinsoc se pode fechar esta issue.
