### ISSUE TITLE
Adicionar dados do GTFS do BRT em dev

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-api#117]
## Objetivo

Subir dados da Transolímpica em dev para teste e validação do FE

- Preencher stop_codes
- Adicionar dados no django

**Comment by gmartinsoc** [comment]
stop_codes 0001 - 0015.
route_types alterados para:

- Ônibus executivo: 200
- SPPO: 700
- BRT: 702
- STPL: 704
- STPC: 1501
