### ISSUE TITLE
Ajuste do filtro por stop_id em stop_times

### ISSUE THREAD

**Issue by gmartinsoc** [RJ-SMTR/mobilidade-rio-api#130]
## Objetivo: 

Com a inclusão do BRT existem estações que possuem mais de uma plataforma para embarque cujo location_type é 1, quando pesquisamos o stop_id em stop_times nesse caso o retorno vazio por tratar-se de uma parent station.  

Quando o location_type for 1 precisamos incluir no retorno as os dados cujo parent_station possui id igual ao id buscado.

**Comment by yxuo** [comment]
## Tarefas

- [ ] Criar branch `stop_id-stoptimes` a partir do ramo `dev`
- [ ] Pesquisar por stop_id se `location_type` = 0 ou seus filhos se `location_type` = 1

**Comment by yxuo** [comment]
## Como usar

> Conteúdo disponível no README deste PR.

* `stop_id` - Filtra por 1 ou mais stop_id
  * Uso: `stop_id=1,2,3`
  * Funcionamento:
    * Se o stop não possuir filhos (`location_type`=0), retorna apenas ele mesmo.
      * Exemplo real: <http://localhost:8010/gtfs/stop_times/?stop_id=2028O00023C0,5144O00512C9>
    * Se o stop for `parent_station` de alguém (`location_type`=1), retorna apenas seus filhos.
      * Exemplo real: <http://localhost:8010/gtfs/stop_times/?stop_id=4128O00169P0,5144O00487P9>
    * ⚠️ Por enquanto não é possível pesquisar por `stop_id` e seus filhos ao mesmo tempo. O primeiro item deste parâmetro valerá para os demais.

**Comment by yxuo** [comment]
Pull Request criado em #131
