### ISSUE TITLE
Atualizar consumo dos dados de ShapeWithStops pelo preditor

### ISSUE THREAD

**Issue by gmartinsoc** [RJ-SMTR/mobilidade-rio-api#133]
## Objetivo

Preditor consome os dados de shapeWithStops de um arquivo, precisamos entregar esses dados por um endpoint na aplicação e eliminar campos que não são necessários.

### Instruções

* em predictor/utils.py:61 (capture_trip_stops), será trocado o shapes_wish_stops.csv pelo uso do endpoint.
  Veja linha 65-66

**Comment by yxuo** [comment]
## Etapas

- [ ] Criar branch `feat/shapes_with_stops-predictor` baseada em `feat/shapes_with_stops`
- [ ] Juntar com branch `feat/preditor`
- [ ] Executar com sucesso usando método original (arquivo csv) de `feat/preditor`
- [ ] Usar o mecanismo do endpoint `shapes_with_stops` no lugar do arquivo csv
- [ ]

**Comment by yxuo** [comment]
Nova tarefa em paralelo:
---
Prefect - pegar dados do BQ e mandar para banco Django

**Comment by yxuo** [comment]
Esta versão do preditor será descontinuada por enquanto.

Dado o pouco tempo que temos optamos por refazer usando um método mais simples.
