### ISSUE TITLE
Atualização sistemática do modelo do preditor

### ISSUE THREAD

**Issue by gmartinsoc** [RJ-SMTR/mobilidade-rio-api#137]
## Objetivo

O modelo de dados do preditor pode perder precisão com o passar do tempo, precisamos atualiza-lo periódicamente.  Precisamos integrar a dinamica de armazenamento/inicialização do modelo na api ao pipeline de geração do mesmo.

**Comment by yxuo** [comment]
O novo preditor fará requisições da API realtime para cada chamada do aplicativo.

Portanto, este recurso não é mais necessário.
