### ISSUE TITLE
Finalizar desenvolvimento do preditor

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-api#139]
> Preencher abaixo:

## O que está em andamento? (+ bloqueios)

1. Endpoint da tabela de predição no Django - [`feat/predictor-v2`](https://github.com/RJ-SMTR/mobilidade-rio-api/tree/feat/predictor-v2)

- Corrigir: Ao gerar predição, `arrival_time` sempre é `NaN`

2. Cronjob para gerar tabela de predição - [`feat/predictor-v2`](https://github.com/RJ-SMTR/mobilidade-rio-api/tree/feat/predictor-v2)
  - Criar um método para atualizar a cada 20 segundos.
  - Testar rotina funcionando em dev

**Comment by fernandascovino** [comment]
@yxuo adicionar links uteis de cada topico do desenvolvimento (brancas ativas, arquitetura do miro, etc...)

**Comment by yxuo** [comment]
Esta issue está relacionada a uma versão descontinuada do preditor.

Novo preditor: #116
