### ISSUE TITLE
Filtrar `stop_times` pela estação correta (stop x parent)

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-api#140]
# Lógica usada
Estação
- No BRT todas as estações são stops (stops pai) e devem ter um `stop_code`.
- Toda estação também é um **stop pai**, portanto não possui `platform_code`.
- Cada estação possui pelo menos 2 plataformas, que também são stops (stops filho).

Plataforma
- Toda plataforma é um **stop filho**, portanto possui `platform_code` igual o `stop_id` de sua estação (stop pai).

Filtragem em stop_times
- Se o stop for stop pai, mostra as trips de seus stops filho.
- Caso contrário, mostra as trips de todos os stops filho

# Tarefas
- [x] Subir PR
- [x] Aprovar PR de feat para `dev`
- [x] Verificar se essa feature ainda é necessária.
- [x] Mapear features em `dev` e discutir se compensa juntar a branch `dev` ou apenas uma branch  com essas features.
- [x] Subir PR para dev - será nosso staging no momento (01/03/2023)

---
Notas para consultar:
- Renomear branch `release/2.2.0-gtfs-transolimpica` na issue #142 
- Criar `release/2.2.0-stop_id-parent-stoptimes` de branch `release/2.2.0-gtfs-transolimpica`
- Cherry pick dessa feature em `feat/stop_id-parent-stoptimes`
- Revisar PR para dar merge em main
- Aprovar PR
- Merge em staging e dev

**Comment by yxuo** [comment]
# Verificar se essa feature ainda é necessária.

Por que essa feature foi criada?

* Apenas as estações (stops pai) tem QRCode.

* O usuário pesquisa pelo QRCode da estação e quer ver as plataformas sentido A e sentido B.

* A lógica usada é: apenas estações têm QR Codes adesivados.  
  E a [convenção do GTFS](https://developers.google.com/transit/gtfs/reference?hl=pt-br#:~:text=este%20campo%20precisa%20ser%20deixado%20em%20branco%20no%20caso%20de%20locais%20que%20nao%20mostram%20um%20codigo%20aos%20passageiros.) diz que`stop_code` é opcional e só aparece em stops (estações ou plataformas) adesivados.

* O GTFS BRT mais atual (snapshot de 27/02/2023 às 11:41) confirma isso.

**Portanto SIM, é necessária.**

**Comment by yxuo** [comment]
# Mapeando branch `dev` vs `main`

> Atualizado até c44578bd58d746790dbbdc9a05f067fb3e951b65 (28/02/2023)

* Feat: stop parent x child em stoptimes
* 23/12/2022 - [`05ff7df...f0900aa`](https://github.com/RJ-SMTR/mobilidade-rio-api/compare/f471396...f0900aa2fe4235b5e2db5cadc7d6066de711b0b9)
  * 26/12/2022 - query para `stop_id__all` em arquivo separado (`query_utils.py`) `fb8255b...2998fb7`, 
  * 27/12/2023 - Atualizar README [`233d909...e31032c`](https://github.com/RJ-SMTR/mobilidade-rio-api/compare/2998fb7939ae88de70669f52401f17c83d47fb69...e31032c038e6b957f63a6975bf322fe8f589eb0d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)
  * 04/01/2023 - correções menores [`b80d1b8...4c89faf`](https://github.com/RJ-SMTR/mobilidade-rio-api/compare/e7eeb51e8757c623a1cfb47450a1216975cf7d1e...4c89faf6ea25af72ec348b54a2f659403fede9f4)
  * 28/02/2023 - correções menores c44578bd58d746790dbbdc9a05f067fb3e951b65

* Feat: mostrar enpoints na página raiz da api
  * 27/12/2023 - [`a959a0e`, `9b19761`](https://github.com/RJ-SMTR/mobilidade-rio-api/compare/00825566c87c2df3144e24d7458c1939561223d8...a959a0e9d13371cced530c1521f029c6c60fa49a)

* Feat: filtrar por `stop_name` em stoptimes
  * 28/12/2022 - [`0e07a73...e4fe73b`](https://github.com/RJ-SMTR/mobilidade-rio-api/compare/0e07a73fe7d04758bc94bfa3ca0ffe06155d6e84...d9c0ee450eefca9a24391d64cd31eab98fb5b94e)

* Hotfix: Deploy para `cd_stag` de qualquer branch /release
  * 29/12/2023 - [`57e4f74...40faf52`](https://github.com/RJ-SMTR/mobilidade-rio-api/compare/e4fe73be98403a16f3397cb6c333768b562a8ca8...40faf528c8213be5540371f9f846ebeb2ddcc745)

* Permitir deploy para `cd_dev` para acertar env
  * 05/02/2023 - [`75d95e1`, `8e66650`, `4b233af`](https://github.com/RJ-SMTR/mobilidade-rio-api/compare/75d95e148c563d7aac6373105daec89504f297a6...4b233afa96e1340b4bee8c6fa5948552011328cd)
    * Alterações em `cd_dev` e `cd_stag`

* Mudanças menores
  * 18/01/2023 - trigger cd a3a92afa32f2399aa3f287501494e2ec03dc4b7e

**Comment by yxuo** [comment]
Como o PR já foi feito para `dev`, esta issue pode fechada.
