### ISSUE TITLE
Corrigir API de staging

### ISSUE THREAD

**Issue by fernandascovino** [RJ-SMTR/mobilidade-rio-api#142]
# Tarefas
Finalizar antes de lançar o app
- [ ] Verificar se precisa aplicar mudanças críticas para o app funcionar corretamente.
  - [x] Comparar staging com main. Se estiver atrás da main, rebase.
    - (23/02/2022) O último commit de main é merge do último commit de staging: 9dcf8089be7e1eb76b95c790edc2dfc0232f1c77
  - [ ] Verificar mudanças relevantes
    > Mudanças em branches como dev, feat e hotfix. Além de coisas necessárias para o novo GTFS.

- [ ] Corrigir certificado de staging

**Comment by yxuo** [comment]
# Verificar mudanças em dev, feat, hotfix...


- [ ] Atualizar o `populate_db.py`
  > Vai ajudar a gerar o banco e se necessário o modelo será ajustado nas configs

- [ ] Certificar que o modelo será compatível com novo GTFS
  > Vai ajudar a gerar o banco e se necessário o modelo será ajustado nas configs

- [ ] Organizar o README para ficar mais apresentável
  - [ ] Revisar os modos de execução e branches, então colocá-los no final.
  - [ ] Conferir se a descrição dos endpoints estão ok
  - Revisar a instalação e afins é **baixa prioridade**
  -

**Comment by yxuo** [comment]
A API de staging foi corrigida ao subir a branch de dev em staging via `release/2.2`.

Portanto esta issue será fechada.
